# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven Build Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v2
    
    - name: Step 2 - Set up JDK 
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Step 3 - Have Github Action Build Maven Project
      run: mvn -B package --file pom.xml
      
    - name: Step 4 - List current directory
      run: ls -a
    
    - name: Step 5 - What is the target folder?
      run: 
        cd target
        ls -a   
