#Code check with SonarCloud
name: SonarCloud
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          java-package: jdk+fx
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Analyze with SonarCload
#         uses: sonarsource/sonarcloud-github-action@master
        run: >
          mvn --batch-mode
          -Pcoverage
          sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=certifaiai
          -Dsonar.projectKey=CertifaiAI_TrainingLabs
          -Dsonar.java.binaries=**/target/classes  
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify 
      
          
